version: '3.8'

services:
  app:
    image: satishri/hlowd-py-gitjendocompose:latest
    container_name: hlowd-py-gitjendocompose
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: hlowd-py-gitjendocomposedb
    environment:
      POSTGRES_USER: satish
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hlowd-py-gitjendocompose
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
